server:
  port: 8082

spring:
  application:
    name: blog-article-service
  datasource:
    url: jdbc:mysql://115.159.59.30:3306/blog_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: Zhangsan+1
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  jwt:
    secret: "请和 user-service 保持一致的一串长随机字符串"
    expiration: 86400000
